version: 2.1
jobs:
  compile:
   docker:
      - image: estillhere/build:kernel
   steps:
      - run:
          command: |
            git clone --recursive https://github.com/estillhere/android_kernel_asus_sdm636 -b clown kernel && cd kernel
            curl https://raw.githubusercontent.com/estillhere/cooking-kernel/builder.ci/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
